name: Issue(edited) Event

on:
  issues:
    types: edited

jobs:
  echo-context:
    runs-on: ubuntu-latest
    steps:
      - name: Echo context
        run: |
          echo '${{ toJSON(github) }}'
