name: Issue(assigned) Event

on:
  issues:
    types: assigned

jobs:
  echo-context:
    runs-on: ubuntu-latest
    steps:
      - name: Echo context
        run: |
          echo '${{ toJSON(github) }}'
