name: Pull Request(edited) Event

on:
  pull_request:
    types: edited

jobs:
  echo-context:
    runs-on: ubuntu-latest
    steps:
      - name: Echo context
        run: |
          echo '${{ toJSON(github) }}'
