name: Pull Request Review Comment Event

on: pull_request_review_comment

jobs:
  echo-context:
    runs-on: ubuntu-latest
    steps:
      - name: Echo context
        run: |
          echo '${{ toJSON(github) }}'
